#!/usr/bin/env bun

import { app, $ } from "@gutenye/script.js";

const { NAME: ENV_NAME } = process.env;

app
  .cmd("b, build", "Build image")
  .add("[name]", "Image name")
  .add(async (name) => {
    const imageName = ENV_NAME ?? name;
    await $`docker build -t ${imageName} .`;
  });

app
  .cmd("push", "Push to remote")
  .add("[name]", "Branch name")
  .add(async (name) => {
    const branch = ENV_NAME ?? name;
    await $`
      git push origin master:${branch}
      git push
    `;
  });
