#!/usr/bin/env bash

build() {
  NAME=${NAME-$1}
  docker build -t $NAME .
}

push() {
  NAME=${NAME-$1}
  git push origin master:$NAME
}

case "$1" in
  b | build ) shift; build "$@" ;;
  push ) shift; push "$@" ;;
esac
