#!/usr/bin/env bash

DEFAULT_PORT=22

project=$1
PORT=${2-DEFAULT_PORT}

echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa
ssh -p $PORT $SERVER "cd /app/$project && docker-compose pull"
ssh -p $PORT $SERVER "cd /app/$project && docker-compose up -d && docker-compose restart"
