#!/usr/bin/env bash

build() {
  docker build -t gutenye/rtorrent-flood:arm .
}

push() {
  git push origin master:rtorrent-flood
  git push
}

case "$1" in
  b | build ) shift; build "$@" ;;
  push ) shift; push "$@" ;;
esac
