#!/usr/bin/env bun

import { app, $ } from "@gutenye/script.js";

app.cmd("b, build", "Build arm image").add(async () => {
  await $`docker build -t gutenye/rtorrent-flood:arm .`;
});

app.cmd("push", "Push to remote").add(async () => {
  await $`
    git push origin master:rtorrent-flood
    git push
  `;
});
