#!/usr/bin/with-contenv bash

s6-setuidgid abc /usr/bin/rtorrent -n -o import=/app/rtorrent/rtorrent.rc

until [ -e "/app/rtorrent/session/rtorrent.lock" ];
do
sleep 1s
done

rtorrent_pid=$(< /app/rtorrent/session/rtorrent.lock cut -d '+' -f 2)
tail -n 1 -f /app/rtorrent/rtorrent.log "$rtorrent_pid"
