name: Build supercronic

on:
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            suffix: amd64
          - platform: linux/arm64
            suffix: arm64
    steps:
      - uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Validate compose file
      #   run: docker compose -f supercronic/compose.yml config -q

      - name: Build image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          compose_file: compose.yml
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          # registry: docker.io
          # image_name: gutenye/supercronic
          # image_tag: latest-${{ matrix.suffix }}
          # context: supercronic
          # dockerfile: supercronic/Dockerfile
          # build_extra_args: --pull --platform=${{ matrix.platform }}

